/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospitalapp;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author peter
 */
public class ProtoEmployeeGUI extends javax.swing.JFrame {
    private ArrayList<ProtoEmployee> employees;
    /**
     * Creates new form HospitalGUI
     */
    public ProtoEmployeeGUI() {
        initComponents();
        NameLbl.setVisible(false);
        roleLbl.setVisible(false);
        empIDLbl.setVisible(false);
        eduLbl.setVisible(false);
        fieldLbl.setVisible(false);
        monthsLbl.setVisible(false);
        hoursLbl.setVisible(false);
        floorLbl.setVisible(false);
        nameTf.setVisible(false);
        roleTf.setVisible(false);
        empIDTf.setVisible(false);
        eduTf.setVisible(false);
        FieldTf.setVisible(false);
        monthsTf.setVisible(false);
        hoursTf.setVisible(false);
        floorTf.setVisible(false);
        employees = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NameLbl = new javax.swing.JLabel();
        roleLbl = new javax.swing.JLabel();
        empIDLbl = new javax.swing.JLabel();
        nameTf = new javax.swing.JTextField();
        roleTf = new javax.swing.JTextField();
        empIDTf = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        displayBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        eduLbl = new javax.swing.JLabel();
        eduTf = new javax.swing.JTextField();
        fieldLbl = new javax.swing.JLabel();
        FieldTf = new javax.swing.JTextField();
        monthsLbl = new javax.swing.JLabel();
        monthsTf = new javax.swing.JTextField();
        hoursLbl = new javax.swing.JLabel();
        floorLbl = new javax.swing.JLabel();
        hoursTf = new javax.swing.JTextField();
        floorTf = new javax.swing.JTextField();
        doctorRb = new javax.swing.JRadioButton();
        nurseRb = new javax.swing.JRadioButton();
        MaintenanceRb = new javax.swing.JRadioButton();
        whichLbl = new javax.swing.JLabel();
        generateBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        outputTa = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Employees ");

        NameLbl.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        NameLbl.setText("name:");

        roleLbl.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        roleLbl.setText("role:");

        empIDLbl.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        empIDLbl.setText("ID:");

        nameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTfActionPerformed(evt);
            }
        });

        empIDTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empIDTfActionPerformed(evt);
            }
        });

        addBtn.setBackground(new java.awt.Color(0, 255, 255));
        addBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        displayBtn.setBackground(new java.awt.Color(0, 255, 255));
        displayBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        displayBtn.setText("display");
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });

        searchBtn.setBackground(new java.awt.Color(0, 255, 255));
        searchBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(0, 255, 255));
        deleteBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        eduLbl.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        eduLbl.setText("Education:");

        fieldLbl.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        fieldLbl.setText("Field:");

        FieldTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldTfActionPerformed(evt);
            }
        });

        monthsLbl.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        monthsLbl.setText("months:");

        monthsTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthsTfActionPerformed(evt);
            }
        });

        hoursLbl.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        hoursLbl.setText("hours:");

        floorLbl.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        floorLbl.setText("Floor:");

        doctorRb.setText("Doctor");
        doctorRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorRbActionPerformed(evt);
            }
        });

        nurseRb.setText("Nurse");
        nurseRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nurseRbActionPerformed(evt);
            }
        });

        MaintenanceRb.setText("Maintenance");
        MaintenanceRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaintenanceRbActionPerformed(evt);
            }
        });

        whichLbl.setText("Choose which Staff to add");

        generateBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        generateBtn.setText("Employee messages");
        generateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateBtnActionPerformed(evt);
            }
        });

        outputTa.setColumns(20);
        outputTa.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        outputTa.setRows(5);
        jScrollPane2.setViewportView(outputTa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(searchBtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(deleteBtn))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(addBtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(displayBtn))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(monthsLbl)
                                            .addComponent(hoursLbl)
                                            .addComponent(floorLbl))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(floorTf, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(hoursTf, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(monthsTf, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(doctorRb)
                                        .addGap(18, 18, 18)
                                        .addComponent(nurseRb)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(MaintenanceRb))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(eduLbl)
                                            .addComponent(empIDLbl)
                                            .addComponent(roleLbl)
                                            .addComponent(NameLbl))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(roleTf, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(empIDTf, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(eduTf, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fieldLbl)
                                .addGap(34, 34, 34)
                                .addComponent(FieldTf, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(generateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(whichLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(whichLbl)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doctorRb)
                    .addComponent(nurseRb)
                    .addComponent(MaintenanceRb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NameLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(roleLbl)
                                    .addComponent(roleTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(empIDLbl)
                                    .addComponent(empIDTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(eduLbl)
                                    .addComponent(eduTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldLbl)
                            .addComponent(FieldTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(generateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(monthsLbl)
                            .addComponent(monthsTf, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hoursLbl)
                            .addComponent(hoursTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(floorLbl)
                            .addComponent(floorTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addBtn)
                            .addComponent(displayBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchBtn)
                            .addComponent(deleteBtn)))
                    .addComponent(nameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTfActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        if(doctorRb.isSelected()){ 
        Doctor d= new Doctor();
           
            d.setName(nameTf.getText());
            d.setEmpId(empIDTf.getText());
            d.setRole(roleTf.getText());
            d.setEducation(eduTf.getText());
            d.setField(FieldTf.getText());
            employees.add(d);
            //clearFields();
        }else if(nurseRb.isSelected()){
            Nurse n= new Nurse();
            n.setName(nameTf.getText());
            n.setEmpId(empIDTf.getText());
            n.setRole(roleTf.getText());
            n.setEducation(eduTf.getText());
            n.setMonths(monthsTf.getText());
            employees.add(n);
        }else if(MaintenanceRb.isSelected()){
            Maintenance m = new Maintenance();
            m.setName(nameTf.getText());
            m.setEmpId(empIDTf.getText());
            m.setRole(roleTf.getText());
            m.setHours(Double.parseDouble(hoursTf.getText()));
            m.setFloor(floorTf.getText());
            employees.add(m);
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
       if(employees.isEmpty()){
            JOptionPane.showMessageDialog(null,"No employees in this system");
        }
        else{
            for(int i = 0; i < employees.size();i++){
                JOptionPane.showMessageDialog(null,employees.get(i).getDetails());
            }
        }
    }//GEN-LAST:event_displayBtnActionPerformed

    private void empIDTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empIDTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empIDTfActionPerformed

    private void FieldTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldTfActionPerformed

    private void doctorRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorRbActionPerformed
        roleLbl.setVisible(true);
        roleTf.setVisible(true);
        empIDLbl.setVisible(true);
        empIDTf.setVisible(true);
        roleTf.setVisible(true);
        NameLbl.setVisible(true);
        nameTf.setVisible(true);
        eduTf.setVisible(true);
        eduLbl.setVisible(true);
        FieldTf.setVisible(true);
        fieldLbl.setVisible(true);
         monthsTf.setVisible(false);
        monthsLbl.setVisible(false);
        hoursTf.setVisible(false);
        hoursLbl.setVisible(false);
        floorTf.setVisible(false);
        floorLbl.setVisible(false);
    }//GEN-LAST:event_doctorRbActionPerformed

    private void nurseRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nurseRbActionPerformed
       roleLbl.setVisible(true);
        roleTf.setVisible(true);
        NameLbl.setVisible(true);
        nameTf.setVisible(true);
        empIDLbl.setVisible(true);
        empIDTf.setVisible(true);
        eduTf.setVisible(true);
        eduLbl.setVisible(true);
        monthsTf.setVisible(true);
        monthsLbl.setVisible(true);
         FieldTf.setVisible(false);
        fieldLbl.setVisible(false);
        hoursTf.setVisible(false);
        hoursLbl.setVisible(false);
        floorTf.setVisible(false);
        floorLbl.setVisible(false);
    }//GEN-LAST:event_nurseRbActionPerformed

    private void MaintenanceRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaintenanceRbActionPerformed
       roleLbl.setVisible(true);
        roleTf.setVisible(true);
        NameLbl.setVisible(true);
        nameTf.setVisible(true);
        empIDLbl.setVisible(true);
        empIDTf.setVisible(true);
        hoursTf.setVisible(true);
        hoursLbl.setVisible(true);
        floorTf.setVisible(true);
        floorLbl.setVisible(true);
        eduTf.setVisible(false);
        eduLbl.setVisible(false);
        FieldTf.setVisible(false);
        fieldLbl.setVisible(false);
         monthsTf.setVisible(false);
        monthsLbl.setVisible(false);
    }//GEN-LAST:event_MaintenanceRbActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        if(employees.isEmpty()){
            JOptionPane.showMessageDialog(null,"No employees to search");
        }
        else{
            String searchTerm = empIDTf.getText();
            for(ProtoEmployee e:employees){
                if(e.getEmpId().equalsIgnoreCase(searchTerm)){
                    JOptionPane.showMessageDialog(null,e.getDetails());
                }
            }
        }    
    }//GEN-LAST:event_searchBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        if(employees.isEmpty()){
            JOptionPane.showMessageDialog(null,"System empty, nothing can be deleted");
        }
        else{
            String searchTerm = empIDTf.getText();
            for(int i = 0; i < employees.size();i++){
                ProtoEmployee e = employees.get(i);
                if(e.getEmpId().equalsIgnoreCase(searchTerm)){
                    employees.remove(e);
                }
            }
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void monthsTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthsTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthsTfActionPerformed

    private void generateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateBtnActionPerformed
        EmpMessage myMessage = new EmpMessage();
        outputTa.setText(myMessage.generateMessage());
    }//GEN-LAST:event_generateBtnActionPerformed

    public static void main(String args[]){
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProtoEmployeeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FieldTf;
    private javax.swing.JRadioButton MaintenanceRb;
    private javax.swing.JLabel NameLbl;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton displayBtn;
    private javax.swing.JRadioButton doctorRb;
    private javax.swing.JLabel eduLbl;
    private javax.swing.JTextField eduTf;
    private javax.swing.JLabel empIDLbl;
    private javax.swing.JTextField empIDTf;
    private javax.swing.JLabel fieldLbl;
    private javax.swing.JLabel floorLbl;
    private javax.swing.JTextField floorTf;
    private javax.swing.JButton generateBtn;
    private javax.swing.JLabel hoursLbl;
    private javax.swing.JTextField hoursTf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel monthsLbl;
    private javax.swing.JTextField monthsTf;
    private javax.swing.JTextField nameTf;
    private javax.swing.JRadioButton nurseRb;
    private javax.swing.JTextArea outputTa;
    private javax.swing.JLabel roleLbl;
    private javax.swing.JTextField roleTf;
    private javax.swing.JButton searchBtn;
    private javax.swing.JLabel whichLbl;
    // End of variables declaration//GEN-END:variables
}
